apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-deployment
  namespace: dev
  
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: danielbachar/nginx_website:latest_dev_image
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: docker-secret
