name: build and push nginx website 
on:

 
 push:
 
  
jobs:
  docker_build_push:
    runs-on: [self-hosted,Linux,X64]
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
      - name: install docker
        run: |
             
             curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add - \
             && add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable" \
             && apt update \
             && apt-cache policy docker-ce \
             && apt install docker-ce -y

         
       

      
          
      - name: docker login 
        run: | 
          
          docker login -u danielbachar -p Efrat40@@
          docker push danielbachar/nginx_website:latest_dev_image
      
      - name: build docker image and push to docker hub 
        run: |
          
          cd images/custom-nginx
          docker build -t danielbachar/nginx_website:latest_dev_image .    
          
          
