name: deploy nginx  to dev namespace

on:
  push:
   
    
jobs:
  checkout:
    runs-on: [self-hosted,Linux,X64]
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3 
      
      - name: use context 
        run: |
        
         kubectl apply -f kubernetes/local-cluster/dev

