name: install docker 
on:
 
 push:
  
jobs:
  docker_build_push:
    runs-on: [self-hosted,Linux,X64]
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
      - name: install docker 
        run: |      
            docker -v
